### ISSUE TITLE
npm run build:flow fails on not finding registry.json

### ISSUE THREAD

**Issue by hanninen** [boyney123/eventbridge-atlas#4]
I wanted to try out the new flow parser, but executing the `npm run build:flow` fails, running on tag `0.4`. All other parsers work fine with my `.env` config.

```shell
npm run build:flow

> eventbridge-atlas@0.0.1 build:flow
> npm run clean --silent && npm run generate --silent -- --format=flow

[1/3] 🔎 Fetching data from AWS...
[2/3] 🧑🏻‍💻 Generating format for desired tool: flow ...
e [Error: ENOENT: no such file or directory, open '/home/aki/src/github/eventbridge-atlas/src/parsers/flow/src/lib/data/registry.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/aki/src/github/eventbridge-atlas/src/parsers/flow/src/lib/data/registry.json'
}
```

**Comment by boyney123** [comment]
Thanks @hanninen I will check it out and see what's going on, will report back 👍

**Comment by boyney123** [comment]
Cool found the issue @hanninen 

If you pull latest should be fixed, let me know if it works 👍

**Comment by hanninen** [comment]
Thanks @boyney123 for the quick fix, managed to generate the docs with the `flow` parse.
