### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by stephenbawks** [boyney123/eventbridge-atlas#7]
`
[1/3] 🔎 Fetching data from AWS...
(node:52080) UnhandledPromiseRejectionWarning: BadRequestException: Unsupported operation.
    at deserializeAws_restJson1ListSchemasCommandError (C:\git\eventbridge-atlas\node_modules\@aws-sdk\client-schemas\protocols\Aws_restJson1.ts:3048:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at C:\git\eventbridge-atlas\node_modules\@aws-sdk\middleware-serde\src\deserializerMiddleware.ts:18:20
    at C:\git\eventbridge-atlas\node_modules\@aws-sdk\middleware-signing\src\middleware.ts:26:22
    at StandardRetryStrategy.retry (C:\git\eventbridge-atlas\node_modules\@aws-sdk\middleware-retry\src\StandardRetryStrategy.ts:83:38)
    at C:\git\eventbridge-atlas\node_modules\@aws-sdk\middleware-logger\src\loggerMiddleware.ts:22:22
(node:52080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)
(node:52080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I am not exactly sure what this error is at this point but my HUNCH is that its probably puking at in internal Private CA.... and the chain possibly not matching....

**Comment by stephenbawks** [comment]
Actually I think is a non-issue.  I was trying to do discovery on an auto-discovered schema and that is when I was getting this error.

**Comment by boyney123** [comment]
Hey @stephenbawks 

Cool, did you manage to get it working OK?

**Comment by boyney123** [comment]
Going to close the issue, unless you can replicate it feel free to reopen :)
