### ISSUE TITLE
No ability to add descriptions for the eventsources at the metadata level

### ISSUE THREAD

**Issue by SeanAlexanderHarris** [boyney123/eventbridge-atlas#9]
Commit 71aa502 seems to remove event-metadata in favour of the newer metadata methods. Thereafter, there is no way to add descriptions for the eventsources themselves as far I can tell from my use of the tool so far. Keeping eventsource descriptions would be cool because it can add valuable context and insight to the meaning &/or purpose of a source's events.

**Comment by boyney123** [comment]
Cool thanks @SeanAlexanderHarris, I will try and take a look and see the best place to add them :)

**Comment by boyney123** [comment]
Hi @SeanAlexanderHarris 

Version 1.1.0 has just been released and I added the ability to add source descriptions again and also maintainers, you can read more here on how to get started: https://eventbridge-atlas.netlify.app/docs/release-notes/1_1_0

Thanks for raising the issue, let me know if you have any more ideas or feedback!

Cheers!

**Comment by SeanAlexanderHarris** [comment]
Hej @boyney123,

Apologies for delay in the thank you. Nice one for sorting that! Really liking the Eventbridge tools you're working on.. keep it up! We're experimenting with using them on our team.

**Comment by boyney123** [comment]
Hey @SeanAlexanderHarris 

Yeah no problem at all, any ideas/feedback just shout happy to explore new features or ideas you all have :)
